name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41aa609b06f696a89b7f2b24190b7e7e95fa7275a4f99dc189928358f301bae5"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
