name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d1d1b92a41f48029727e83026c628e04b335529f26c36162c2f41b72fc01e16"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
