name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.1.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0aae90695c190913757170f38a88a9433d8bb1241d46c391aa5fe1e60567bc85"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
