name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bce080d18ee33dbaeb2551abc06b0ec49f2c86db211b69c46fa0df81520c8d8d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
