name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7681a1b7943cd9efde0cc5a54b6bc02cb274d9df348f844c4896b5ffa977fea3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
