name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1de1431d419913fa98766fb47a9d96c7abb4eae07a5db43ebf4988b36ad8517d"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
