name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a9acee179daabb972e9b407f09dd60a2f6fe3693649d4181148353b24287c12"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
