name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.2.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23599c90eb5fefe57726d6efb4c765b2b28f0b8e1873c922cba1958d6ebcf89d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
