name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fdc905e2d64b257cb519269ef614623b1396cb99fe659dc30330bc8f87b5318"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
