name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2983a6ad7a3fbab17cbad85963d62178b14af5f8f848d2164c189ca9988dea0a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
