name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac29d9814d26d99f42ef7a8d8b4d888395302ce55d35937f1e6a889c96352e95"

[versions]
fabric = "0.19.3"
minecraft = "1.21.8"
