name = "Badly Optimized"
author = "Yiss"
version = "1.0.0+26.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e594ab838d747aa3433c2ef9fe5a6e96ef457434e9613a4d861f093ab298e1bf"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
